### ISSUE TITLE
Data Visualization and Charting

### ISSUE THREAD

**Issue by gokatz** [EmberMap/video-requests#1]
Ha... I'm the first... 💪 Data Visualization and Charting in Ember (D3, Chart.js, DC...) 🌈

**Comment by samselikoff** [comment]
Oh nice... I did this a bunch when I started Ember. If you had to pick 1 thing what would it be? General intro? How to make a bar chart? etc

**Comment by gokatz** [comment]
Of course, a brief intro about canvas or SVG with a basic example. Mainly, the list of available plugins and what could I choose as there is some handful of options available out there  ??

**Comment by snewcomer** [comment]
I would also be interested in understanding and integrating D3 w/ the component lifecycle.  ie. how to draw chart, receive new data & update chart.  For example, if you select a new option to filter on, the component that renders the d3 image changes as well.
